//! Resolve libmpv's `MPV_RENDER_PARAM_*` values for the software renderer.
//!
//! These are plain C enum positions, and mpv has *moved* them across releases
//! (the DRM render params were dropped, shifting `SW_SIZE..SW_POINTER` from
//! 18..21 down to 17..20). Hard-coding them blindly is how you get silent
//! memory corruption, so:
//!
//! 1. if the build machine has mpv's headers, read the real values from them;
//! 2. otherwise fall back to the values verified against mpv 0.41, and the
//!    runtime gate in `ffi::MpvLib::load` refuses embedded playback on libmpv
//!    versions we have not verified.
//!
//! The build never fails: if the headers cannot be found or parsed, we use the
//! defaults.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

/// The values verified against mpv 0.41.0 / client API 2.5.
const FALLBACK: &[(&str, i32)] = &[
    ("SW_SIZE", 17),
    ("SW_FORMAT", 18),
    ("SW_STRIDE", 19),
    ("SW_POINTER", 20),
    ("BLOCK_FOR_TARGET_TIME", 12),
];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let header = find_render_header();
    let (values, source) = match header.as_deref().and_then(parse_render_header) {
        Some(parsed) => (parsed, "mpv headers"),
        None => (FALLBACK.to_vec(), "built-in defaults (mpv 0.41)"),
    };

    let mut out = String::new();
    let _ = writeln!(out, "// @generated by build.rs - resolved from {source}");
    for (name, value) in &values {
        let _ = writeln!(out, "pub const {name}: i32 = {value};");
    }
    let from_headers = header.is_some() && source == "mpv headers";
    let _ = writeln!(out, "pub const RESOLVED_FROM_HEADERS: bool = {from_headers};");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("mpv_layout.rs");
    std::fs::write(&dest, out).expect("writing generated mpv layout");

    if !from_headers {
        // Worth surfacing: it means we could not verify the layout against the
        // local mpv, so embedded playback is gated on a known-good API version.
        println!(
            "cargo:warning=reel-player: mpv headers not found; using built-in \
             MPV_RENDER_PARAM values and gating embedded playback on libmpv API >= 2.5"
        );
    }
}

fn find_render_header() -> Option<PathBuf> {
    // Prefer pkg-config, which is what a distro user will have.
    if let Ok(out) = Command::new("pkg-config")
        .args(["--variable=includedir", "mpv"])
        .output()
    {
        if out.status.success() {
            let dir = String::from_utf8_lossy(&out.stdout).trim().to_string();
            if !dir.is_empty() {
                let candidate = Path::new(&dir).join("mpv/render.h");
                if candidate.is_file() {
                    return Some(candidate);
                }
            }
        }
    }

    [
        "/usr/include/mpv/render.h",
        "/usr/local/include/mpv/render.h",
        "/opt/homebrew/include/mpv/render.h",
        "/usr/include/x86_64-linux-gnu/mpv/render.h",
    ]
    .iter()
    .map(PathBuf::from)
    .find(|p| p.is_file())
}

/// Pull `MPV_RENDER_PARAM_<NAME> = <n>` out of render.h.
fn parse_render_header(path: &Path) -> Option<Vec<(&'static str, i32)>> {
    let text = std::fs::read_to_string(path).ok()?;

    let mut values = Vec::new();
    for (name, _) in FALLBACK {
        let needle = format!("MPV_RENDER_PARAM_{name}");
        let value = text.lines().find_map(|line| {
            let line = line.trim();
            let rest = line.strip_prefix(&needle)?;
            let rest = rest.trim_start().strip_prefix('=')?;
            let digits: String = rest
                .trim_start()
                .chars()
                .take_while(|c| c.is_ascii_digit())
                .collect();
            digits.parse::<i32>().ok()
        })?;
        values.push((*name, value));
    }
    Some(values)
}
